services:
  backend_dev:
    profiles: ["dev"]
    build:
      context: ./backend/vendora
    env_file:
      - ./backend/vendora/.env
      - ./stripe/webhook.env
    ports:
      - "8000:8000"
    depends_on:
      db_dev:
        condition: service_healthy
    volumes:
      - ./backend/vendora:/app
    command: python manage.py runserver 0.0.0.0:8000 --noreload

  db_dev:
    profiles: ["dev", "test"]
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  customer-page:
    profiles: ["dev"]
    container_name: customer-page-dev
    working_dir: /app
    build:
      context: ./frontend/customer-page
      dockerfile: Dockerfile
    volumes:
      - ./frontend/customer-page:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host --port 5173
    env_file:
      - ./frontend/customer-page/.env

  stripe-cli-subscriptions:
    profiles: ["dev"]
    image: stripe/stripe-cli:latest
    container_name: stripe-cli-subscriptions
    env_file:
      - ./backend/vendora/.env
    environment:
      STRIPE_API_KEY: ${STRIPE_PRIVATE}
    command: >
      listen
      --forward-to http://host.docker.internal:8000/subscriptions/stripe/webhook/
      --events checkout.session.completed,customer.subscription.created

  stripe-cli-payments:
    profiles: ["dev"]
    image: stripe/stripe-cli:latest
    container_name: stripe-cli-payments
    env_file:
      - ./backend/vendora/.env
    environment:
      STRIPE_API_KEY: ${STRIPE_PRIVATE}
    command: >
      listen
      --forward-to http://host.docker.internal:8000/payments/stripe/webhook/
      --events payment_intent.succeeded,invoice.payment_succeeded

  backend_test:
    profiles: ["test"]
    build:
      context: ./backend/vendora
    env_file:
      - ./backend/vendora/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/vendora:/app
    command: python manage.py test
