services:
  backend_dev:
    profiles: ["dev"]
    build:
      context: ./backend/vendora
    env_file:
      - ./backend/vendora/.env
      - ./stripe/webhook.env
    ports:
      - "8000:8000"
    depends_on:
      db_dev:
        condition: service_healthy
    volumes:
      - ./backend/vendora:/app
    command: python manage.py runserver 0.0.0.0:8000 --noreload

  db_dev:
    profiles: ["dev", "test"]
    image: mysql:8.0
    env_file:
      - .env
    ports:
      - "3306:3306"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 5s
      timeout: 5s
      retries: 5

  customer-page:
    profiles: ["dev"]
    container_name: customer-page-dev
    working_dir: /app
    build:
      context: ./frontend/customer-page
      dockerfile: Dockerfile
    volumes:
      - ./frontend/customer-page:/app
      - /app/node_modules
    ports:
      - "5173:5173"
    command: npm run dev -- --host --port 5173
    env_file:
      - ./frontend/customer-page/.env

  stripe-cli:
    profiles: [ "dev" ]
    image: stripe/stripe-cli:latest
    container_name: stripe-cli
    env_file:
      - ./backend/vendora/.env
    volumes:
      - ./stripe:/app/stripe
    working_dir: /app
    entrypoint: [ "/bin/sh" ]
    command: [ "-c", "sleep infinity" ]


  backend_test:
    profiles: ["test"]
    build:
      context: ./backend/vendora
    env_file:
      - ./backend/vendora/.env
    ports:
      - "8000:8000"
    volumes:
      - ./backend/vendora:/app
    command: python manage.py test
